# If you do not have OpenSSL installed, update
# the following line to use "http://" instead
source 'https://rubygems.org'
gem 'pry'

gem "middleman", "~>3.4.0"

# Live-reloading plugin
gem "middleman-livereload", "~> 3.1.0"

gem 'font-awesome-sass', '~> 4.7'

gem 'bootstrap-sass', '~> 3.3.6'

